FROM node:14-alpine

RUN apk add --no-cache tini

COPY applications/client-app/package.json .
COPY yarn.lock .

ENV NODE_ENV=production

RUN yarn install --frozen-lockfile --ignore-optional

USER node

COPY --chown=node:node applications/client-app/server.mjs .

ENTRYPOINT ["/sbin/tini", "--", "node"]

CMD ["./server.mjs"]
