
serve:
  cookies:
    same_site_mode: Lax

urls:
  self:
    issuer: http://id.kratos.com/k/hydra
  consent: http://id.kratos.com/oauth/authorize
  login: http://id.kratos.com/oauth/login
  logout: http://id.kratos.com/logout

secrets:
  system:
    - $SECRET

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
    pairwise:
      salt: $PAIRWISE_SALT
