
serve:
  cookies:
    same_site_mode: Lax

urls:
  self:
    issuer: http://127.0.0.1:4444
  consent: http://127.0.0.1:4455/oauth/authorize
  login: http://127.0.0.1:4455/oauth/login
  logout: http://127.0.0.1:4455/logout

secrets:
  system:
    - $SECRET

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
    pairwise:
      salt: $PAIRWISE_SALT
